// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6vPJaUxZemJiLxHH2DC5k8l7G9IbeuVM',
    appId: '1:953085909678:web:8e3dae474f9cb48e31eb3f',
    messagingSenderId: '953085909678',
    projectId: 'carekudos-d1b04',
    authDomain: 'carekudos-d1b04.firebaseapp.com',
    storageBucket: 'carekudos-d1b04.firebasestorage.app',
    measurementId: 'G-ESRSCQDJZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3a-LXJ7vEPAHOvM6rZV8jtiQVC6Or4n8',
    appId: '1:953085909678:android:dafc5e3aa58a022531eb3f',
    messagingSenderId: '953085909678',
    projectId: 'carekudos-d1b04',
    storageBucket: 'carekudos-d1b04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTs-IIjTfkheuDeDTGOqXqkdERGRHYwtQ',
    appId: '1:953085909678:ios:b6599b31677902fc31eb3f',
    messagingSenderId: '953085909678',
    projectId: 'carekudos-d1b04',
    storageBucket: 'carekudos-d1b04.firebasestorage.app',
    iosBundleId: 'com.pearl.carekudos-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTs-IIjTfkheuDeDTGOqXqkdERGRHYwtQ',
    appId: '1:953085909678:ios:b6599b31677902fc31eb3f',
    messagingSenderId: '953085909678',
    projectId: 'carekudos-d1b04',
    storageBucket: 'carekudos-d1b04.firebasestorage.app',
    iosBundleId: 'com.pearl.carekudos-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVGgnM44dCLyZu6WpNocJPXB7FJYmTArI',
    appId: '1:919426591664:web:d8eb3e4bfb929a3bb68475',
    messagingSenderId: '919426591664',
    projectId: 'carekudos-1',
    authDomain: 'carekudos-1.firebaseapp.com',
    storageBucket: 'carekudos-1.firebasestorage.app',
    measurementId: 'G-K8RQD4NY73',
  );
}
