// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVGgnM44dCLyZu6WpNocJPXB7FJYmTArI',
    appId: '1:919426591664:web:b38aba27e01e54e5b68475',
    messagingSenderId: '919426591664',
    projectId: 'carekudos-1',
    authDomain: 'carekudos-1.firebaseapp.com',
    storageBucket: 'carekudos-1.firebasestorage.app',
    measurementId: 'G-W3DD0EK051',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFZg3gJRfVM0no2M6S9o6xlIvdiqCJ_EM',
    appId: '1:919426591664:android:ac4ee37f1d4d0189b68475',
    messagingSenderId: '919426591664',
    projectId: 'carekudos-1',
    storageBucket: 'carekudos-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtt7MsZRNuhuHG_bCimhRv5IAggpO5kKk',
    appId: '1:919426591664:ios:adad9a529308dd39b68475',
    messagingSenderId: '919426591664',
    projectId: 'carekudos-1',
    storageBucket: 'carekudos-1.firebasestorage.app',
    iosBundleId: 'com.example.carekudosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtt7MsZRNuhuHG_bCimhRv5IAggpO5kKk',
    appId: '1:919426591664:ios:adad9a529308dd39b68475',
    messagingSenderId: '919426591664',
    projectId: 'carekudos-1',
    storageBucket: 'carekudos-1.firebasestorage.app',
    iosBundleId: 'com.example.carekudosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVGgnM44dCLyZu6WpNocJPXB7FJYmTArI',
    appId: '1:919426591664:web:d8eb3e4bfb929a3bb68475',
    messagingSenderId: '919426591664',
    projectId: 'carekudos-1',
    authDomain: 'carekudos-1.firebaseapp.com',
    storageBucket: 'carekudos-1.firebasestorage.app',
    measurementId: 'G-K8RQD4NY73',
  );
}
